
import java.awt.HeadlessException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DEVESH_G
 */
public class BloodDonation extends javax.swing.JFrame {
SimpleDateFormat date;
ResultSet rs;
PreparedStatement pt;
int x;
long n;

/** Creates new form Blood */
    public BloodDonation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btndonate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtaadhardonate = new javax.swing.JTextField();
        Combodonatetype = new javax.swing.JComboBox<>();
        Donationdate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Donation");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("Donation type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Donation Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("Aadhar ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        btndonate.setBackground(new java.awt.Color(51, 51, 0));
        btndonate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btndonate.setForeground(new java.awt.Color(255, 255, 0));
        btndonate.setText("Donate");
        btndonate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black));
        btndonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonateActionPerformed(evt);
            }
        });
        getContentPane().add(btndonate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 70, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 0));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("Close");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 70, -1));

        txtaadhardonate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtaadhardonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaadhardonateActionPerformed(evt);
            }
        });
        getContentPane().add(txtaadhardonate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 130, -1));

        Combodonatetype.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Combodonatetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donation Type", "Blood ", "Platelet", "plasma" }));
        getContentPane().add(Combodonatetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 130, -1));

        Donationdate.setDateFormatString("yyyy-MM-dd");
        Donationdate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(Donationdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 130, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\donate.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonateActionPerformed
    try {
        DBconnect connect=new DBconnect();
        String q=" select * from registration_table where aadhar_number=?";
        pt = connect.con.prepareStatement(q);
        n=Long.parseLong(txtaadhardonate.getText());
        pt.setLong(1,n);   
        rs= connect.view(pt);
        if(rs.next()==false)
        {
            JOptionPane.showMessageDialog(this, "First register your self.");
            Registration reg=new Registration();
            reg.setVisible(true);
        } 
        else 
        {   
            String w="insert into donation_table values(?,?,?)";
            pt = connect.con.prepareStatement(w);
            pt.setLong(1,n); 
            if(Combodonatetype.getSelectedIndex()>=1) 
            {
                pt.setString(2,Combodonatetype.getItemAt(Combodonatetype.getSelectedIndex()));
            }
            SimpleDateFormat sd;
            sd = new SimpleDateFormat("yyyy-MM-dd");
            String da= sd.format(Donationdate.getDate());
            pt.setString(3,da);
            x=connect.Insert(pt);
            if(x==1)
            {
                JOptionPane.showMessageDialog(this, "Thanks for your donation.");
                                try
                {
                    String q1="update registration_table set LAST_DONATION_DATE=? where aadhar_number="+n+"";
                    pt = connect.con.prepareStatement(q1);
                    //pt.setLong(1,Long.parseLong(txtaadhardonate.getText()));
                    Date d=Donationdate.getDate();
                    DateFormat dx=new SimpleDateFormat("yyyy-MM-dd");
                    pt.setString(1,dx.format(d));
                    connect.Update(pt);    
                }
                catch(NumberFormatException | SQLException e)
                {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
                txtaadhardonate.setText(null);
                Combodonatetype.setSelectedIndex(0); 
                Donationdate.setCalendar(null);
            }
        }
    } 
    catch (HeadlessException | NumberFormatException | SQLException ex) 
    {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_btndonateActionPerformed

    private void txtaadhardonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaadhardonateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaadhardonateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuBar mb=new MenuBar();
        this.hide();
        mb.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodDonation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combodonatetype;
    private com.toedter.calendar.JDateChooser Donationdate;
    private javax.swing.JButton btndonate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtaadhardonate;
    // End of variables declaration//GEN-END:variables

}
