
import com.mysql.cj.log.Log;
import java.util.logging.*;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.util.regex.*;


/**
 *
 * @author DEVESH_G
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    PreparedStatement pt;
    ResultSet rs;
    String i,name,aa;
    int x;
    public long aadhar;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new java.awt.TextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnlogin = new java.awt.Button();
        jLab = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtaadharval = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setText("Login ID/ Aadhar Number");

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setText("LOGIN PAGE");

        jLabel3.setBackground(new java.awt.Color(204, 0, 204));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Don't have account Sign-Up now ?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        txtid.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtpass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setText("Password");

        btnlogin.setBackground(new java.awt.Color(0, 153, 153));
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnlogin.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnlogin.setLabel("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        jLab.setBackground(new java.awt.Color(0, 0, 0,1));
        jLab.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\padlock.png")); // NOI18N
        jLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel1))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLab))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtpass.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 390));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\log.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtaadharval.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtaadharval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaadharvalActionPerformed(evt);
            }
        });
        getContentPane().add(txtaadharval, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 220, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
    try
    {
        DBconnect connect=new DBconnect();
        i=txtid.getText();
        Pattern p=Pattern.compile("[^a-zA-Z0-9]");
        Pattern pat=Pattern.compile("^[A-Za-z]++$");
        Matcher m= p.matcher(i);
        Matcher mt= pat.matcher(i);
        if(mt.find() || m.find())
        {
            pt=connect.con.prepareStatement("select aadhar_number, NAME from registration_table where id=? and Password=?");
            pt.setString(1,i);
            pt.setString(2,txtpass.getText());
            rs=connect.view(pt);
            if(rs.next()==true)
            {
                aadhar=Long.parseLong(rs.getString("aadhar_number"));
                name=rs.getString("NAME");
                aa=String.valueOf(aadhar);
                txtaadharval.setText(aa);
                JOptionPane.showMessageDialog(this, "welcome "+name);
                this.hide();
                MenuBar b=new MenuBar();
                b.txtaadharval1.setText(txtaadharval.getText());
                b.setVisible(true);
            }
        }
        else if(txtid.getText().equals("")&& txtpass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Field is empty.");
            txtid.requestFocus();
        }
        else
        {
            aadhar= Long.parseLong(i);
            pt=connect.con.prepareStatement("select name from registration_table where aadhar_number=? and Password=?");
            pt.setLong(1,aadhar);
            pt.setString(2,txtpass.getText());
            rs=connect.view(pt);
            if(rs.next()==true)
            {
                name=rs.getString("name");
                txtaadharval.setText(String.valueOf(aadhar));
                JOptionPane.showMessageDialog(this, "welcome "+name);
                this.hide();
                MenuBar b=new MenuBar();
                b.txtaadharval1.setText(txtaadharval.getText());
                b.setVisible(true);
            }
        }
        connect.con.close();  
    }
    catch(HeadlessException | NumberFormatException  e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    } 
    catch (SQLException ex) 
    {
        Logger.getLogger(Log.class.getName()).log(Level.SEVERE, null, ex.getMessage());
    }
    }//GEN-LAST:event_btnloginActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Registration re=new Registration();
        this.hide();
        re.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabMousePressed
    if(jLab.isEnabled())
    {
        txtpass.setEchoChar((char)0);
    }
    }//GEN-LAST:event_jLabMousePressed

    private void jLabMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabMouseReleased
    if(jLab.isEnabled())
    {
        txtpass.setEchoChar('*');
    }
    }//GEN-LAST:event_jLabMouseReleased

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
    txtid.requestFocus();    
    }//GEN-LAST:event_txtidActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
    txtpass.requestFocus(); 
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtaadharvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaadharvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaadharvalActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtaadharval.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnlogin;
    private javax.swing.JLabel jLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtaadharval;
    public java.awt.TextField txtid;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
