/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DEVESH_G
 */
import java.awt.*;
import java.sql.*;
import java.text.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.regex.*;
import javax.swing.*;
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Radiogroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        checkmark = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Combogroup = new javax.swing.JComboBox<>();
        txtconpass = new java.awt.TextField();
        txtname = new java.awt.TextField();
        txtfather_husbandname = new java.awt.TextField();
        txtnumber = new java.awt.TextField();
        txtaadhar = new java.awt.TextField();
        Radiofemale = new javax.swing.JRadioButton();
        Radioother = new javax.swing.JRadioButton();
        Radiomale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        txtlastdate = new com.toedter.calendar.JDateChooser();
        txtdob = new com.toedter.calendar.JDateChooser();
        btnreset = new java.awt.Button();
        btnsubmit = new java.awt.Button();
        txtpass = new java.awt.TextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Page");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        checkmark.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        checkmark.setText("For First Time");
        checkmark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkmarkMouseClicked(evt);
            }
        });
        checkmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkmarkActionPerformed(evt);
            }
        });
        getContentPane().add(checkmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel2.setText("REGISTRATION FORM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("LAST DONATE DATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("FATHER/HUSBAND NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("D.O.B");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("AADHAAR NUMBER");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("BLOOD GROUP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("GENDER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setText("PHONE NUMBER");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("NAME");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.5F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        jSeparator1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 45, 830, 8));

        Combogroup.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Combogroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Group", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        getContentPane().add(Combogroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 200, -1));

        txtconpass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtconpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 190, -1));

        txtname.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, -1));

        txtfather_husbandname.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtfather_husbandname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        txtnumber.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumberKeyPressed(evt);
            }
        });
        getContentPane().add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 170, -1));

        txtaadhar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtaadhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaadharKeyPressed(evt);
            }
        });
        getContentPane().add(txtaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 170, -1));

        Radiogroup.add(Radiofemale);
        Radiofemale.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Radiofemale.setText("FEMALE");
        getContentPane().add(Radiofemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        Radiogroup.add(Radioother);
        Radioother.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Radioother.setText("OTHER");
        Radioother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiootherActionPerformed(evt);
            }
        });
        getContentPane().add(Radioother, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, -1, -1));

        Radiogroup.add(Radiomale);
        Radiomale.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Radiomale.setText("MALE");
        getContentPane().add(Radiomale, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, 110));

        txtlastdate.setDateFormatString("yyyy-MM-dd");
        txtlastdate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtlastdate.setPreferredSize(new java.awt.Dimension(8, 12));
        getContentPane().add(txtlastdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 190, 25));

        txtdob.setDateFormatString("yyyy-MM-dd");
        txtdob.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 180, 25));

        btnreset.setBackground(new java.awt.Color(130, 108, 125));
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnreset.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnreset.setLabel("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 160, -1));

        btnsubmit.setBackground(new java.awt.Color(130, 108, 125));
        btnsubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnsubmit.setLabel("SUBMIT");
        btnsubmit.setName(""); // NOI18N
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 160, -1));

        txtpass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(0, 0, 0));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 190, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setText("PASSWORD");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 0, 204));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 204));
        jLabel11.setText("Already account Sign-In now ?");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\DOCTER .png")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RadiootherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiootherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadiootherActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtname.setText(null);
        txtfather_husbandname.setText(null);
        txtnumber.setText(null);
        txtaadhar.setText(null);
        txtdob.setCalendar(null);
        if(Radiomale.isSelected())
        {
            Radiogroup.clearSelection();
            //Radiomale.remove(this);
        }
        else if(Radiofemale.isSelected()) 
        {
            Radiogroup.clearSelection();
            //Radiofemale.remove(this);
        }           
        else
        {
            Radiogroup.clearSelection();
            //Radioother.remove(this);
        }
        txtpass.setText(null);
        txtconpass.setText(null);
        txtlastdate.setCalendar(null);
        txtaddress.setText(null);
        Combogroup.setSelectedIndex(0);
        txtname.requestFocus();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
    try
    {
        String r_val = "0123456789@#$&*?"+"ABCDEFGHIJKLMNOPQRSTUVWXYZ#@$*?"+"0123456789@#$&*?"+ "abcdefghijklmnopqrstuvxyz#@$*?";         Random rand = new Random();
        StringBuilder b = new StringBuilder();
        while (b.length() < 8)
        {
            b.append(r_val.charAt((int)(rand.nextDouble()*r_val.length())));
        }
        String id=b.toString();
        DBconnect connect=new DBconnect();
        PreparedStatement pt=connect.con.prepareStatement("insert into registration_table values(?,?,?,?,?,?,?,?,?,?,?)");
        pt.setString(1, id);
        pt.setString(2, txtname.getText());
        pt.setString(3, txtfather_husbandname.getText());
        Pattern p = Pattern.compile("(0/91)?[7-9][0-9]{9}"); 
        Matcher m = p.matcher(txtnumber.getText());
        if (m.matches()) 
        {
            pt.setLong(4, Long.parseLong(txtnumber.getText()));
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Enter correct Phone Number");  
        }                
        Pattern pd = Pattern.compile("^[2-9]{1}[0-9]{3}[0-9]{4}[0-9]{4}$"); 
        Matcher mc = pd.matcher(txtaadhar.getText());
        if (mc.matches()) 
        {
            pt.setLong(5, Long.parseLong(txtaadhar.getText()));
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Enter correct Aadhaar Number");  
        } 
        SimpleDateFormat sd;
        sd = new SimpleDateFormat("yyyy-MM-dd");
        String da= sd.format(txtdob.getDate());
        DateTimeFormatter dt=DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime ld= LocalDateTime.now();
        String d=dt.format(ld);
        LocalDate Ld= LocalDate.parse(da);
        LocalDate LdL= LocalDate.parse(d);
        int x=Ld.getYear();
        int y=LdL.getYear();
        if((y-x)>=18)
        {
        pt.setString(6,da);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"18+ Only.");  
        }
        if(txtpass.getText().equals(txtconpass.getText()))
        {
            pt.setString(7,txtpass.getText()); 
        }  
        else
        {
            JOptionPane.showMessageDialog(this, "Password Missmatch.");
        }
         if(checkmark.isSelected())
        {
            pt.setDate(8,java.sql.Date.valueOf("1947-08-15"));
        }
        else
        {
        pt.setString(8,sd.format(txtlastdate.getDate()));
        }
        pt.setString(9, txtaddress.getText());
        if(Radiomale.isSelected())
        {
            pt.setString(10,Radiomale.getText());
        }
        else if(Radiofemale.isSelected()) 
        {
            pt.setString(10,Radiofemale.getText());
        }           
        else
        {
            pt.setString(10,Radioother.getText());
        }
        if(Combogroup.getSelectedIndex()>=1) 
        {
           pt.setString(11,Combogroup.getItemAt(Combogroup.getSelectedIndex()));
        }
        int r= connect.Insert(pt);
        if(r==1)
        {
            JOptionPane.showMessageDialog(this, """
                                                Registration Successsfull.
                                                 Your Id: """+id);
             txtname.setText(null);
             txtfather_husbandname.setText(null);
             txtnumber.setText(null);
             txtaadhar.setText(null);
             txtdob.setCalendar(null);
             txtpass.setText(null);
             txtconpass.setText(null);
             txtlastdate.setCalendar(null);
             txtaddress.setText(null);
             if(Radiomale.isSelected())
            {
                Radiogroup.clearSelection();
            }
            else if(Radiofemale.isSelected()) 
            {
                Radiogroup.clearSelection();
            }           
            else
            {
                Radiogroup.clearSelection();
            }
            Combogroup.setSelectedIndex(0); 
            this.hide();
            Login ob=new Login();
            ob.txtid.setText(id);
            ob.setVisible(true);
            connect.con.close();  
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Registration Unsuccesssfull.");
        }
        connect.con.close();
    }    
    catch(HeadlessException | NumberFormatException | SQLException e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void checkmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkmarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkmarkActionPerformed

    private void txtnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumberKeyPressed
         String v=txtnumber.getText();
      int l=v.length();
      if(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9')
      {
          txtnumber.setEditable(true);
      }
      else
      {
        txtnumber.setEditable(false);
        JOptionPane.showMessageDialog(null,"Enter numeric digit only.");
      }
    }//GEN-LAST:event_txtnumberKeyPressed

    private void txtaadharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaadharKeyPressed
        String v=txtaadhar.getText();
      int l=v.length();
      if(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9')
      {
          txtaadhar.setEditable(true);
      }
      else
      {
        txtaadhar.setEditable(false);
        JOptionPane.showMessageDialog(null,"Enter numeric digit only.");
      }
    }//GEN-LAST:event_txtaadharKeyPressed

    private void checkmarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkmarkMouseClicked
        txtlastdate.setEnabled(false);
    }//GEN-LAST:event_checkmarkMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Login re=new Login();
        this.hide();
        re.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registration().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combogroup;
    private javax.swing.JRadioButton Radiofemale;
    private javax.swing.ButtonGroup Radiogroup;
    private javax.swing.JRadioButton Radiomale;
    private javax.swing.JRadioButton Radioother;
    private java.awt.Button btnreset;
    private java.awt.Button btnsubmit;
    private javax.swing.JCheckBox checkmark;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField txtaadhar;
    private javax.swing.JTextArea txtaddress;
    private java.awt.TextField txtconpass;
    private com.toedter.calendar.JDateChooser txtdob;
    private java.awt.TextField txtfather_husbandname;
    private com.toedter.calendar.JDateChooser txtlastdate;
    private java.awt.TextField txtname;
    private java.awt.TextField txtnumber;
    private java.awt.TextField txtpass;
    // End of variables declaration//GEN-END:variables
}
