/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DEVESH_G
 */
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.*;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    Date ds,da;
    SimpleDateFormat date;
    ResultSet rs;
    PreparedStatement pt;
    long x;
    String num;
    public Update() {
        initComponents();
    }
//    public Update(long a)
//    {
//        this.x=a;
//        //num=String.valueOf(x);
//        this.txtaadhar.setText(String.valueOf(x));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Radiogroup = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        txtlastdate = new com.toedter.calendar.JDateChooser();
        txtdob = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        GENDER = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtname = new java.awt.TextField();
        txtfat_husName = new java.awt.TextField();
        txtnumber = new java.awt.TextField();
        txtpass = new java.awt.TextField();
        txtaadhar = new java.awt.TextField();
        Radiomale = new javax.swing.JRadioButton();
        Radiofemale = new javax.swing.JRadioButton();
        Radioother = new javax.swing.JRadioButton();
        Combogroup = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txtupdate = new javax.swing.JButton();
        txtcancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtgroup = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\2381638.png")); // NOI18N
        jLabel14.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Donor Page");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtlastdate.setDateFormatString("yyyy-MM-dd");
        txtlastdate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(txtlastdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 260, 30));

        txtdob.setDateFormatString("yyyy-MM-dd");
        txtdob.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 260, 30));

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("ADDRESS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("BLOOD GROUP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, 20));

        jLabel5.setBackground(new java.awt.Color(0, 153, 204));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("LAST DONATE DATE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 20));

        jLabel7.setBackground(new java.awt.Color(0, 153, 204));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("PHONE NUMBER");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 153, 204));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("D.O.B");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 153, 204));
        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("PASSWORD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        GENDER.setBackground(new java.awt.Color(0, 153, 204));
        GENDER.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        GENDER.setText("GENDER");
        getContentPane().add(GENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("UPDATE DONOR");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 290, 50));

        txtname.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 260, 30));

        txtfat_husName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(txtfat_husName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 260, 30));

        txtnumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 260, 30));

        txtpass.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 310, 30));

        txtaadhar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(txtaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 310, 30));

        Radiogroup.add(Radiomale);
        Radiomale.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Radiomale.setForeground(new java.awt.Color(0, 0, 255));
        Radiomale.setText("MALE");
        getContentPane().add(Radiomale, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        Radiogroup.add(Radiofemale);
        Radiofemale.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Radiofemale.setForeground(new java.awt.Color(0, 0, 255));
        Radiofemale.setText("FEMALE");
        getContentPane().add(Radiofemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        Radiogroup.add(Radioother);
        Radioother.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Radioother.setForeground(new java.awt.Color(0, 0, 255));
        Radioother.setText("OTHER");
        getContentPane().add(Radioother, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, -1, -1));

        Combogroup.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Combogroup.setForeground(new java.awt.Color(51, 0, 153));
        Combogroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Group", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        Combogroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombogroupActionPerformed(evt);
            }
        });
        getContentPane().add(Combogroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 150, 30));

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 300, 110));

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\search.png")); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, new java.awt.Color(0, 153, 153), java.awt.Color.black, java.awt.Color.darkGray));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 110, -1));

        txtupdate.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        txtupdate.setForeground(new java.awt.Color(0, 0, 204));
        txtupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\4391443.png")); // NOI18N
        txtupdate.setText("UPDATE");
        txtupdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 153, 153), java.awt.Color.black, java.awt.Color.darkGray));
        txtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 130, -1));

        txtcancel.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        txtcancel.setForeground(new java.awt.Color(0, 0, 204));
        txtcancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\close Jframe.png")); // NOI18N
        txtcancel.setText("CLOSE");
        txtcancel.setActionCommand("CANCEL");
        txtcancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, new java.awt.Color(0, 153, 153), java.awt.Color.black, java.awt.Color.darkGray));
        txtcancel.setMaximumSize(new java.awt.Dimension(111, 37));
        txtcancel.setMinimumSize(new java.awt.Dimension(111, 37));
        txtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcancelActionPerformed(evt);
            }
        });
        getContentPane().add(txtcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 130, 40));

        jLabel12.setBackground(new java.awt.Color(0, 153, 204));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("FATHER/HUSBAND NAME");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 20));

        jLabel13.setBackground(new java.awt.Color(0, 153, 204));
        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("NAME");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(java.awt.Color.blue);
        jLabel15.setText("Enter Aadhar Number");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.5F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        jSeparator1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1020, 20));

        txtgroup.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(txtgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 180, 30));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEVESH_G\\Documents\\NetBeansProjects\\Blood_&_Oxygen_Bank\\img\\human.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1050, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try
       {
           DBconnect connect=new DBconnect();
           pt=connect.con.prepareStatement("select * from registration_table where aadhar_number=?");
           pt.setLong(1, Long.parseLong(txtaadhar.getText()));
           rs = connect.view(pt);
           if(rs.next()==true)
            {
                txtname.setText(rs.getString(2));
                txtfat_husName.setText(rs.getString(3));
                txtnumber.setText(rs.getString(4));
                date=new SimpleDateFormat("yyyy-MM-dd");
               try 
               {
                   ds = (Date) date.parse(rs.getString(6));
                   da = (Date) date.parse(rs.getString(8));
                   txtdob.setDate(ds);
                   txtlastdate.setDate(da);
               } 
               catch (ParseException ex) 
               {
                   Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex.getMessage());
               }
                String gender=rs.getString(10);
                switch (gender) 
                {
                   case "MALE" -> Radiomale.setSelected(true);
                   case "FEMALE" -> Radiofemale.setSelected(true);
                   case "OTHER" -> Radioother.setSelected(true);
                   default ->
                   {
                   }
               } 
                txtpass.setText(rs.getString(7));        
                txtaddress.setText(rs.getString(9));
                String b=rs.getString(11); 
                txtgroup.setText(b);   
            }  
       connect.con.close();
       }
       catch(NumberFormatException | SQLException ex)
       {
           JOptionPane.showMessageDialog(this, ex.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupdateActionPerformed
    try
    {        
        DBconnect connect=new DBconnect();
        String q="update registration_table set name=?,FATHER_HUSBAND_NAME=?,PASSWORD=?,PHONE_NUMBER=?,DATE_OF_BIRTH=?,LAST_DONATION_DATE=?,ADDRESS=?,GENDER=?,BLOOD_GROUP=? where aadhar_number=?";
        pt = connect.con.prepareStatement(q);
        pt.setString(1,txtname.getText());
        pt.setString(2,txtfat_husName.getText());                     
        pt.setString(3,txtpass.getText());
        pt.setLong(4,Long.parseLong(txtnumber.getText()));
        Date d=txtdob.getDate();
        DateFormat dx=new SimpleDateFormat("yyyy-MM-dd");
        pt.setString(5,dx.format(d));
        Date dg=txtlastdate.getDate();
        pt.setString(6,dx.format(dg));
        pt.setString(7,txtaddress.getText());
        if(Radiomale.isSelected())
        {
            pt.setString(8,Radiomale.getText());
        }
        else if(Radiofemale.isSelected()) 
        {
            pt.setString(8,Radiofemale.getText());
        }           
        else
        {
            pt.setString(8,Radioother.getText());
        }
        pt.setString(9,txtgroup.getText());
        pt.setLong(10,Long.parseLong(txtaadhar.getText()));
        
        int x=JOptionPane.showConfirmDialog(this, "Are you sure for Updation ?","Select",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            int f=connect.Update(pt);
            if(f==1)
        {
            JOptionPane.showMessageDialog(this, f+" Record Updated.");
            txtname.setText(null);
            txtfat_husName.setText(null);
            txtnumber.setText(null);
            txtaadhar.setText(null);
            txtdob.setCalendar(null);
            if(Radiomale.isSelected())
            {
                Radiogroup.clearSelection();
            }
            else if(Radiofemale.isSelected()) 
            {
                Radiogroup.clearSelection();   
            }           
            else
            {
                Radiogroup.clearSelection();
            }
            txtpass.setText(null);
            txtgroup.setText(null);
            txtlastdate.setCalendar(null);
            txtaddress.setText(null);
            Combogroup.setSelectedIndex(0);
            txtaadhar.requestFocus();
        }
        }
       connect.con.close(); 
        
    }
       catch(NumberFormatException | SQLException ex)
       {
           JOptionPane.showMessageDialog(this, ex.getMessage());
       }
    }//GEN-LAST:event_txtupdateActionPerformed

    private void txtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcancelActionPerformed
        MenuBar mb=new MenuBar();
        mb.txtaadharval1.setText(txtaadhar.getText());
        this.hide();
        mb.setVisible(true);
    }//GEN-LAST:event_txtcancelActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void CombogroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombogroupActionPerformed
        if(Combogroup.getSelectedIndex()>=1) 
        {
            String x;
            x = Combogroup.getItemAt(Combogroup.getSelectedIndex());
            txtgroup.setText(x);
            }    }//GEN-LAST:event_CombogroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Update().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combogroup;
    private javax.swing.JLabel GENDER;
    private javax.swing.JRadioButton Radiofemale;
    private javax.swing.ButtonGroup Radiogroup;
    private javax.swing.JRadioButton Radiomale;
    private javax.swing.JRadioButton Radioother;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public java.awt.TextField txtaadhar;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JButton txtcancel;
    private com.toedter.calendar.JDateChooser txtdob;
    private java.awt.TextField txtfat_husName;
    private java.awt.TextField txtgroup;
    private com.toedter.calendar.JDateChooser txtlastdate;
    private java.awt.TextField txtname;
    private java.awt.TextField txtnumber;
    private java.awt.TextField txtpass;
    private javax.swing.JButton txtupdate;
    // End of variables declaration//GEN-END:variables

    private void convertUtilDateToSqlDate(Date date) 
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
